#!/bin/bash

echo "***** commit-msg file is working! ******"

local_branch="$(git rev-parse --abbrev-ref HEAD)"

commit_message_file=$1

# Throw error if the message is empty
if [[ -z $(grep '[^[:space:]]' $commit_message_file) ]] ; then
    echo "You can't just commit without a message !!" >&2
    exit 1
fi

# regex to validate in commit msg
commit_regex='(TEST-[0-9]+)'
error_msg="Aborting commit. Your commit message is missing either a JIRA Issue ('ALS-1111')"

if ! grep -iqE "$commit_regex" "$commit_message_file"; then
    echo "$error_msg" >&2
    exit 1
fi


