#!/bin/bash

echo "***** commit-msg file is working! ******"

local_branch="$(git rev-parse --abbrev-ref HEAD)"

COMMIT_MSG_FILE=$1


# Throw error if the message is empty
if [[ -z $(grep '[^[:space:]]' $COMMIT_MSG_FILE) ]] ; then
    echo "You can't just commit without a message !!" >&2
    exit 1
fi

